### ISSUE TITLE
Not loading gettext locales (v1.3)

### ISSUE THREAD

**Issue by BrummbQ** [kipcole9/cldr#32]
Hi, 
How am I supposed to use cldr with gettext in a phoenix app? I configure my Gettext module properly and set it in the cldr config. But Cldr.known_gettext_locale_names just returns []

Surprisingly, if I change your code to
```
  @known_gettext_locale_names Config.gettext_locales()
                              |> Enum.map(&Locale.locale_name_from_posix/1)

  @spec known_gettext_locale_names :: [Locale.locale_name(), ...] | []
  def known_gettext_locale_names do
    Config.gettext_locales()
    |> Enum.map(&Locale.locale_name_from_posix/1)
  end
```

Everything is working as expected. Somehow the gettext locales are not available at compile time

**Comment by kipcole9** [comment]
Curious, I can't current reproduce what you're seeing.  I have made the change to use:
```
Config.gettext_locales()
    |> Enum.map(&Locale.locale_name_from_posix/1)
```
Since that is much better than the 'old' code I had.  Thanks very much for spotting this.

I'll continue to test to see if I can reproduce.  I have updated master on GitHub with the changes you proposed though so I wonder if you are still seeing the issue.  Would you be able to check against the GitHub master branch?

**Comment by kipcole9** [comment]
I'm still not able to reproduce.  I have released version 1.3.1 to fix #33 that you reported which also has some very slight changes to the code in this area.

Would you mind checking in 1.3.1 resolves this?  If not I will continue to work out what the issue is.

**Comment by kipcole9** [comment]
Thanks very much for the investigation and demo app, I really appreciate it.  I will work out whats going on over the weekend with an objective to resolve and release by the end of the weekend.

**Comment by kipcole9** [comment]
I have fixed this in the master branch and will push it as [ex_cldr version
1.3.2](https://hex.pm/packages/ex_cldr). There was one bug relating to the detection of the default
locale for a Gettext backend (i.e. like `LocaleBugWeb.Gettext` in your example). But there is also
a couple of misconfigurations.

In your example `config :locale_bug, LocaleBugWeb.Gettext, default_locale: "en", locales: ~w(en de
fr it es)` you have used the config key `locales: ~w(en de fr it es)`. `:locales` is not actually a
valid configuration key for a `Gettext` backend. `Gettext` locales are configured by `.po` files
which are automatically detected in the `priv` directory of your app.

I suspect what you meant to configure is the following:

```
config :ex_cldr,  
  locales: ~w(en de fr it es),
  gettext: LocaleBugWeb.Gettext

config :locale_bug, LocaleBugWeb.Gettext, 
  default_locale: "en" 
``` 

Which will download and configure in Cldr the locales specified (`~w(en de fr it es)`). It will
also configure in Cldr any locales defined for `Gettext` (i.e. in `.po` files).

I will review the documentation and see how I can make the configuration part clearer.

**Comment by BrummbQ** [comment]
Thanks for your work, but I'm afraid its still not working out :/ You can reproduce the bug another way:
1. configure gettext and cldr your way
2. compile cldr
3. run iex interactively: `iex -S mix`
4. Execute Cldr.known_gettext_locale_names
```
iex(1)> Cldr.known_gettext_locale_names
[]
```
But:
```
iex(2)> Cldr.Config.gettext_locales
["de", "en", "es", "fr", "it"]
```
For me the SetLocale plug is still not doing his job. If I access a german route (via path parameter), cldr correctly translates to german, but gettext is always set to en, the default. If I override the gettext locale manually it's translating to german too.

**Comment by kipcole9** [comment]
Would you mind configuring to run off the GitHub master branch while we work this out?

The loading issue I have finally worked out and I understand why its not an issue in my dev environment.  Its not possible at compile time to derive the Gettext locale names.  I've changed it to now be a runtime concern and the test app now delivers the correct locales.  I am hopeful this also resolves the Plug.SetLocale issue.

**Comment by kipcole9** [comment]
I still have a couple of collateral issues to now fix since there are other areas that have been depending on that (incorrect) compile time optimisation.  Working on them now.

**Comment by kipcole9** [comment]
Turns out is a design flaw which means this is going to take a bit of a rethink about how I can determine at dependency compile time what the configured Gettext locale names are.  And it may not be possible.

May I suggest for the moment that you change your configuration to duplicate the Gettext locale configuration in Cldr - so that at least you can move forward while I a new design approach?
```
config :ex_cldr,  
  # Configure manually the locales defined for Gettext
  locales: ~w(en de),
  gettext: LocaleBugWeb.Gettext

config :locale_bug, LocaleBugWeb.Gettext, 
  default_locale: "en" 
```

**Comment by kipcole9** [comment]
I'm also reverting the previous commit referenced two messages above - its the wrong strategy.  I need to fix the design flaw if I can.

That means for now `Cldr.known_gettext_locale_names` will still return `[]` because at compile time I can't currently determine them.  `Cldr.Config.gettext_locales` will return the correct result because it executes at runtime.

**Comment by kipcole9** [comment]
Its been an interesting journey but I have found a reasonable way to solve this issue - and as a side affect Cldr will now recompile itself if it detects a locale configuration change.

The underlying issue is that Elixir will compile dependencies before compiling the host application.  This means, of course, that the `Gettext` module in the host application is not available when `Cldr` is compiled.  And therefore it can't detect the locales configured in Gettext.

By adding a "cldr compiler" in `mix.exs` it is now possible to detect when the locale configuration has changed and then recompile any module that depends on `Cldr.Config` which is where the locale configuration sensitivity lies.

The configuration change for an app is below.  Note that the `[:cldr]` compiler should be the last compiler in the list.
```elixir
  def project do
    [
      app: :app_name,
      ...
      compilers: Mix.compilers ++ [:cldr],
      start_permanent: Mix.env == :prod,
      deps: deps()
    ]
  end
```

This [commit](https://github.com/kipcole9/cldr/commit/027154cd6730569123ed275ec7696eae1e9cc16a) adds the compiler.  I have tested it using the [locale_bug](https://github.com/BrummbQ/locale_bug) app you kindly provided.

I have one more issue to resolve before a release related to dependency trees (this is not an issue for [locale_bug](https://github.com/BrummbQ/locale_bug) test app).

**Comment by kipcole9** [comment]
I have just now pushed what I hope is the [final commit](https://github.com/kipcole9/cldr/commit/6710d200331f26dd6e50bf1ceadd86c87df483ff) to address this issue.  I've been testing it for a while but its a manual process - I haven't found a good test approach for this yet.  I have one more scenario to test which is when the changed configuration requires downloading a Cldr locale.

If you of a mind to try this version by configuring in mix.exs:
```elixir
def project do
  [
    app: :app_name,
    ...
    compilers: Mix.compilers ++ [:cldr],
    start_permanent: Mix.env == :prod,
    deps: deps()
  ]
end

def deps() do
  ...
  {:ex__cldr, git: "https://github.com/kipcole9/cldr"}
end
```
Then of course `mix deps.get` and you should be good to go.

If no further errors are detected I will issue a new release on hex early next week.

**Comment by BrummbQ** [comment]
Hello, Thanks for your work, I tried to follow but it was a little bit hard :)

Anyway, with your latest commit...
First try I just updated ex_cldr and the configuration and rebuild my existing project:
```
== Compilation error in file deps/ex_cldr_units/lib/cldr/unit.ex ==
** (CompileError) deps/ex_cldr_units/lib/cldr/unit.ex:1: cannot define module Cldr.Unit because it is currently being defined in deps/ex_cldr_units/lib/cldr/unit.ex:1
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:194: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

== Compilation error in file deps/ex_cldr_units/lib/cldr/unit.ex ==
** (CompileError) deps/ex_cldr_units/lib/cldr/unit.ex:1: cannot define module Cldr.Unit because it is currently being defined in deps/ex_cldr_units/lib/cldr/unit.ex:1
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:194: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```
Then I cleared my build and started again:
```
== Compilation error in file lib/lad_web/router.ex ==
** (UndefinedFunctionError) function Cldr.Plug.SetLocale.init/1 is undefined (module Cldr.Plug.SetLocale is not available)
    Cldr.Plug.SetLocale.init([apps: [:gettext, :cldr], from: [:path, :session], gettext: LadWeb.Gettext])
    (plug) lib/plug/builder.ex:193: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:181: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:181: Plug.Builder.compile/3
    lib/lad_web/router.ex:4: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```
So I'm not sure what this means, but I can't start the application right now

**Comment by kipcole9** [comment]
Thanks for your patience.  I tested with Cldr, Cldr_Numbers and Cldr_Dates_Times but not Cldr_Units.  There was an issue with `ex_cldr_units` which I had to fix and I have now [published version 1.1.1 on hex](https://hex.pm/packages/ex_cldr_units).

If you 
```
rm -rf _build
mix hex.update ex_cldr_units
``` 
and then try recompiling I think we may be able to move forward.  I am still using your test app and using the same dependencies so I think we're in sync currenctly.

**Comment by BrummbQ** [comment]
Okay great, almost there:
```
...updating and compiling...
== Compilation error in file lib/lad_web/router.ex ==
** (UndefinedFunctionError) function Cldr.Plug.SetLocale.init/1 is undefined (module Cldr.Plug.SetLocale is not available)
    Cldr.Plug.SetLocale.init([apps: [:gettext, :cldr], from: [:path, :session], gettext: LadWeb.Gettext])
    (plug) lib/plug/builder.ex:193: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:181: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:181: Plug.Builder.compile/3
    lib/lad_web/router.ex:4: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
[~/projects/lad]$ mix deps.compile ex_cldr --force                                                                                                                                                                               *[master] 
==> ex_cldr
Compiling 2 files (.erl)
Compiling 31 files (.ex)
Generating Cldr for 7 locales named ["de", "en", "en-001", "es", "fr", ...] with a default locale named "en-001"
Generated ex_cldr app
[~/projects/lad]$ mix phx.server                                                                                                                                                                                                 *[master] 
Compiling 62 files (.ex)
Generated lad app
warning: String.strip/1 is deprecated, use String.trim/1
  /home/greg/projects/lad/deps/poison/mix.exs:4

Recompiling 21 modules from [:ex_cldr, :ex_cldr_dates_times, :ex_cldr_languages, :ex_cldr_lists, :ex_cldr_numbers, :ex_cldr_territories, :ex_cldr_units] due to a locale configuration change
Generating Cldr for 6 locales named ["de", "en", "es", "fr", "it", ...] with a default locale named "en"
```
And its up and running.

Ironically I need to run `mix deps.compile ex_cldr --force` first before I can start the app. It kinda contradicts the "auto-recompile" feature doesn't it? :)

**Comment by kipcole9** [comment]
Wow:
```
Recompiling 21 modules from [:ex_cldr, :ex_cldr_dates_times, :ex_cldr_languages, :ex_cldr_lists, :ex_cldr_numbers, :ex_cldr_territories, :ex_cldr_units] due to a locale configuration change
```
Thats a lot of Cldr :-) Very happy we're nearly there but it shouldn't be necessary to force recompile `ex_cldr`. And:
```
** (UndefinedFunctionError) function Cldr.Plug.SetLocale.init/1 is undefined (module Cldr.Plug.SetLocale is not available)
```
Is clearly not right either (and its not happening in my testing either).

Does it happen if you delete all the build artefacts and clean compile?  i.e.:
```
rm -rf _build
mix phx.server
```

**Comment by kipcole9** [comment]
Fixed the issue with plug compiling by adding Phoenix as a dependency (optional) so that `plug` is compiled before `ex_cldr`.  On the test app it now compiles correctly without any errors.  Would you mind trying one more time?
```
mix deps.update ex_cldr
rm -rf _build
mix phx.server
```
Fingers crossed.

**Comment by kipcole9** [comment]
After some more testing I've elected to publish a release candidate.  I've tested it agains the `locale_bug` app with all Cldr dependent apps configured and it seems to work correctly.  Would you consider trying it on your end.  In your mix.exs:
```
      {:ex_cldr, "1.4.0-rc.0", override: true},
```
Let me know how that goes?

**Comment by BrummbQ** [comment]
Sry, I was busy the last couple of days.

But I just updated my app to rc3 and everything is working as expected now. We are good to go!

**Comment by kipcole9** [comment]
Thanks for the feedback. I've got a couple of commits to go before 1.4 gets released (to do with the `:cldr` compiler on Elixir 1.5 which requires a different approach since there is no `Mix.Task.Xref.calls/0`.  I'll close this issue.

Thanks very much for your collaboration and patience - this was an interesting journey and give me a few ideas for restructuring for Cldr 2.0.
